# TCL File Generated by Component Editor 18.1
# Sun Jun 09 21:35:44 EDT 2019
# DO NOT MODIFY


# 
# GameBoy_Cartridge "GameBoy_Cartridge" v1.0
#  2019.06.09.21:35:44
# GameBoy Cartridge
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module GameBoy_Cartridge
# 
set_module_property DESCRIPTION "GameBoy Cartridge"
set_module_property NAME GameBoy_Cartridge
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP GameBoy
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME GameBoy_Cartridge
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL GameBoy_Cartridge
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file GameBoy_Cartridge.sv SYSTEM_VERILOG PATH GameBoy_Cartridge.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point GameBoy_Cartridge
# 
add_interface GameBoy_Cartridge conduit end
set_interface_property GameBoy_Cartridge associatedClock ""
set_interface_property GameBoy_Cartridge associatedReset ""
set_interface_property GameBoy_Cartridge ENABLED true
set_interface_property GameBoy_Cartridge EXPORT_OF ""
set_interface_property GameBoy_Cartridge PORT_NAME_MAP ""
set_interface_property GameBoy_Cartridge CMSIS_SVD_VARIABLES ""
set_interface_property GameBoy_Cartridge SVD_ADDRESS_GROUP ""

add_interface_port GameBoy_Cartridge CART_ADDR cart_addr Input 16
add_interface_port GameBoy_Cartridge CART_RD cart_rd Input 1
add_interface_port GameBoy_Cartridge CART_WR cart_wr Input 1
add_interface_port GameBoy_Cartridge CART_DATA_in cart_data_in Output 8
add_interface_port GameBoy_Cartridge CART_DATA_out cart_data_out Input 8


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock
set_interface_property avalon_master associatedReset reset
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master address address Output 26
add_interface_port avalon_master read read Output 1
add_interface_port avalon_master readdata readdata Input 8
add_interface_port avalon_master waitrequest waitrequest Input 1
add_interface_port avalon_master write write Output 1
add_interface_port avalon_master writedata writedata Output 8


# 
# connection point reset_gameboy
# 
add_interface reset_gameboy reset start
set_interface_property reset_gameboy associatedClock clock_gameboy
set_interface_property reset_gameboy associatedDirectReset ""
set_interface_property reset_gameboy associatedResetSinks ""
set_interface_property reset_gameboy synchronousEdges DEASSERT
set_interface_property reset_gameboy ENABLED true
set_interface_property reset_gameboy EXPORT_OF ""
set_interface_property reset_gameboy PORT_NAME_MAP ""
set_interface_property reset_gameboy CMSIS_SVD_VARIABLES ""
set_interface_property reset_gameboy SVD_ADDRESS_GROUP ""

add_interface_port reset_gameboy GB_rst reset Output 1


# 
# connection point hps_slave
# 
add_interface hps_slave avalon end
set_interface_property hps_slave addressUnits WORDS
set_interface_property hps_slave associatedClock clock
set_interface_property hps_slave associatedReset reset
set_interface_property hps_slave bitsPerSymbol 8
set_interface_property hps_slave burstOnBurstBoundariesOnly false
set_interface_property hps_slave burstcountUnits WORDS
set_interface_property hps_slave explicitAddressSpan 0
set_interface_property hps_slave holdTime 0
set_interface_property hps_slave linewrapBursts false
set_interface_property hps_slave maximumPendingReadTransactions 0
set_interface_property hps_slave maximumPendingWriteTransactions 0
set_interface_property hps_slave readLatency 0
set_interface_property hps_slave readWaitTime 1
set_interface_property hps_slave setupTime 0
set_interface_property hps_slave timingUnits Cycles
set_interface_property hps_slave writeWaitTime 0
set_interface_property hps_slave ENABLED true
set_interface_property hps_slave EXPORT_OF ""
set_interface_property hps_slave PORT_NAME_MAP ""
set_interface_property hps_slave CMSIS_SVD_VARIABLES ""
set_interface_property hps_slave SVD_ADDRESS_GROUP ""

add_interface_port hps_slave hps_address address Input 26
add_interface_port hps_slave hps_read read Input 1
add_interface_port hps_slave hps_write write Input 1
add_interface_port hps_slave hps_writedata writedata Input 8
add_interface_port hps_slave hps_waitrequest waitrequest Output 1
add_interface_port hps_slave hps_readdata readdata Output 8
set_interface_assignment hps_slave embeddedsw.configuration.isFlash 0
set_interface_assignment hps_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment hps_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment hps_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock_gameboy
# 
add_interface clock_gameboy clock start
set_interface_property clock_gameboy associatedDirectClock ""
set_interface_property clock_gameboy clockRate 0
set_interface_property clock_gameboy clockRateKnown false
set_interface_property clock_gameboy ENABLED true
set_interface_property clock_gameboy EXPORT_OF ""
set_interface_property clock_gameboy PORT_NAME_MAP ""
set_interface_property clock_gameboy CMSIS_SVD_VARIABLES ""
set_interface_property clock_gameboy SVD_ADDRESS_GROUP ""

add_interface_port clock_gameboy SYNC_clk clk Output 1


# 
# connection point LEDR
# 
add_interface LEDR conduit end
set_interface_property LEDR associatedClock ""
set_interface_property LEDR associatedReset ""
set_interface_property LEDR ENABLED true
set_interface_property LEDR EXPORT_OF ""
set_interface_property LEDR PORT_NAME_MAP ""
set_interface_property LEDR CMSIS_SVD_VARIABLES ""
set_interface_property LEDR SVD_ADDRESS_GROUP ""

add_interface_port LEDR LEDR ledr Output 10

