# TCL File Generated by Component Editor 18.1
# Wed Jun 26 17:17:34 EDT 2019
# DO NOT MODIFY


# 
# GameBoy_Audio "GameBoy_Audio" v1.0
#  2019.06.26.17:17:34
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module GameBoy_Audio
# 
set_module_property DESCRIPTION ""
set_module_property NAME GameBoy_Audio
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP GameBoy
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME GameBoy_Audio
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL GameBoy_Audio
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file GameBoy_Audio.sv SYSTEM_VERILOG PATH GameBoy_Audio.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point GameBoy_Audio
# 
add_interface GameBoy_Audio conduit end
set_interface_property GameBoy_Audio associatedClock ""
set_interface_property GameBoy_Audio associatedReset ""
set_interface_property GameBoy_Audio ENABLED true
set_interface_property GameBoy_Audio EXPORT_OF ""
set_interface_property GameBoy_Audio PORT_NAME_MAP ""
set_interface_property GameBoy_Audio CMSIS_SVD_VARIABLES ""
set_interface_property GameBoy_Audio SVD_ADDRESS_GROUP ""

add_interface_port GameBoy_Audio GB_LOUT lout Input 16
add_interface_port GameBoy_Audio GB_ROUT rout Input 16


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst reset Input 1


# 
# connection point avalon_streaming_right
# 
add_interface avalon_streaming_right avalon_streaming start
set_interface_property avalon_streaming_right associatedClock clock
set_interface_property avalon_streaming_right associatedReset reset_sink
set_interface_property avalon_streaming_right dataBitsPerSymbol 8
set_interface_property avalon_streaming_right errorDescriptor ""
set_interface_property avalon_streaming_right firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_right maxChannel 0
set_interface_property avalon_streaming_right readyLatency 0
set_interface_property avalon_streaming_right ENABLED true
set_interface_property avalon_streaming_right EXPORT_OF ""
set_interface_property avalon_streaming_right PORT_NAME_MAP ""
set_interface_property avalon_streaming_right CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_right SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_right right_data data Output 16
add_interface_port avalon_streaming_right right_ready ready Input 1
add_interface_port avalon_streaming_right right_valid valid Output 1


# 
# connection point avalon_streaming_left
# 
add_interface avalon_streaming_left avalon_streaming start
set_interface_property avalon_streaming_left associatedClock clock
set_interface_property avalon_streaming_left associatedReset reset_sink
set_interface_property avalon_streaming_left dataBitsPerSymbol 8
set_interface_property avalon_streaming_left errorDescriptor ""
set_interface_property avalon_streaming_left firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_left maxChannel 0
set_interface_property avalon_streaming_left readyLatency 0
set_interface_property avalon_streaming_left ENABLED true
set_interface_property avalon_streaming_left EXPORT_OF ""
set_interface_property avalon_streaming_left PORT_NAME_MAP ""
set_interface_property avalon_streaming_left CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_left SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_left left_data data Output 16
add_interface_port avalon_streaming_left left_valid valid Output 1
add_interface_port avalon_streaming_left left_ready ready Input 1

