# TCL File Generated by Component Editor 18.1
# Tue Jun 18 23:56:27 EDT 2019
# DO NOT MODIFY


# 
# GameBoy_VGA "GameBoy_VGA" v1.0
#  2019.06.18.23:56:27
# The VGA output for GameBoy Display
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module GameBoy_VGA
# 
set_module_property DESCRIPTION "The VGA output for GameBoy Display"
set_module_property NAME GameBoy_VGA
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP GameBoy
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME GameBoy_VGA
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL GameBoy_VGA
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file GameBoy_VGA.sv SYSTEM_VERILOG PATH GameBoy_VGA.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point GameBoy_Pixel
# 
add_interface GameBoy_Pixel conduit end
set_interface_property GameBoy_Pixel associatedClock GameBoy_clock
set_interface_property GameBoy_Pixel associatedReset ""
set_interface_property GameBoy_Pixel ENABLED true
set_interface_property GameBoy_Pixel EXPORT_OF ""
set_interface_property GameBoy_Pixel PORT_NAME_MAP ""
set_interface_property GameBoy_Pixel CMSIS_SVD_VARIABLES ""
set_interface_property GameBoy_Pixel SVD_ADDRESS_GROUP ""

add_interface_port GameBoy_Pixel LD ld Input 2
add_interface_port GameBoy_Pixel PX_VALID px_valid Input 1


# 
# connection point VGA
# 
add_interface VGA conduit end
set_interface_property VGA associatedClock clock
set_interface_property VGA associatedReset ""
set_interface_property VGA ENABLED true
set_interface_property VGA EXPORT_OF ""
set_interface_property VGA PORT_NAME_MAP ""
set_interface_property VGA CMSIS_SVD_VARIABLES ""
set_interface_property VGA SVD_ADDRESS_GROUP ""

add_interface_port VGA VGA_B vga_b Output 8
add_interface_port VGA VGA_BLANK_n vga_blank_n Output 1
add_interface_port VGA VGA_CLK vga_clk Output 1
add_interface_port VGA VGA_G vga_g Output 8
add_interface_port VGA VGA_HS vga_hs Output 1
add_interface_port VGA VGA_R vga_r Output 8
add_interface_port VGA VGA_SYNC_n vga_sync_n Output 1
add_interface_port VGA VGA_VS vga_vs Output 1


# 
# connection point GameBoy_clock
# 
add_interface GameBoy_clock clock end
set_interface_property GameBoy_clock clockRate 0
set_interface_property GameBoy_clock ENABLED true
set_interface_property GameBoy_clock EXPORT_OF ""
set_interface_property GameBoy_clock PORT_NAME_MAP ""
set_interface_property GameBoy_clock CMSIS_SVD_VARIABLES ""
set_interface_property GameBoy_clock SVD_ADDRESS_GROUP ""

add_interface_port GameBoy_clock GameBoy_clk clk Input 1


# 
# connection point GameBoy_reset
# 
add_interface GameBoy_reset reset end
set_interface_property GameBoy_reset associatedClock clock
set_interface_property GameBoy_reset synchronousEdges DEASSERT
set_interface_property GameBoy_reset ENABLED true
set_interface_property GameBoy_reset EXPORT_OF ""
set_interface_property GameBoy_reset PORT_NAME_MAP ""
set_interface_property GameBoy_reset CMSIS_SVD_VARIABLES ""
set_interface_property GameBoy_reset SVD_ADDRESS_GROUP ""

add_interface_port GameBoy_reset GameBoy_reset reset Input 1


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock
set_interface_property avalon_slave associatedReset reset
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave writedata writedata Input 8
add_interface_port avalon_slave write write Input 1
add_interface_port avalon_slave chipselect chipselect Input 1
add_interface_port avalon_slave address address Input 21
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock_vga
# 
add_interface clock_vga clock end
set_interface_property clock_vga clockRate 0
set_interface_property clock_vga ENABLED true
set_interface_property clock_vga EXPORT_OF ""
set_interface_property clock_vga PORT_NAME_MAP ""
set_interface_property clock_vga CMSIS_SVD_VARIABLES ""
set_interface_property clock_vga SVD_ADDRESS_GROUP ""

add_interface_port clock_vga clk_vga clk Input 1

