# TCL File Generated by Component Editor 18.1
# Tue Jun 04 15:02:56 EDT 2019
# DO NOT MODIFY


# 
# GameBoy_Joypad "GameBoy_Joypad" v1.0
#  2019.06.04.15:02:56
# Gameboy Joypad
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module GameBoy_Joypad
# 
set_module_property DESCRIPTION "Gameboy Joypad"
set_module_property NAME GameBoy_Joypad
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP GameBoy
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME GameBoy_Joypad
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL GameBoy_Joypad
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file GameBoy_Joypad.sv SYSTEM_VERILOG PATH GameBoy_Joypad.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point GameBoy_JoyPad
# 
add_interface GameBoy_JoyPad conduit end
set_interface_property GameBoy_JoyPad associatedClock ""
set_interface_property GameBoy_JoyPad associatedReset ""
set_interface_property GameBoy_JoyPad ENABLED true
set_interface_property GameBoy_JoyPad EXPORT_OF ""
set_interface_property GameBoy_JoyPad PORT_NAME_MAP ""
set_interface_property GameBoy_JoyPad CMSIS_SVD_VARIABLES ""
set_interface_property GameBoy_JoyPad SVD_ADDRESS_GROUP ""

add_interface_port GameBoy_JoyPad P10 p10 Output 1
add_interface_port GameBoy_JoyPad P11 p11 Output 1
add_interface_port GameBoy_JoyPad P12 p12 Output 1
add_interface_port GameBoy_JoyPad P13 p13 Output 1
add_interface_port GameBoy_JoyPad P14 p14 Input 1
add_interface_port GameBoy_JoyPad P15 p15 Input 1


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock
set_interface_property avalon_slave associatedReset reset
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave chipselect_slv chipselect Input 1
add_interface_port avalon_slave write_slv write Input 1
add_interface_port avalon_slave writedata_slv writedata Input 8
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0

